### ISSUE TITLE
Planets and Craft etc disappear after sign in

### ISSUE THREAD

**Issue by 19mw84** [Blaarkies/ksp-visual-calculator#65]
After signing in, the planets, orbits, craft and planet selector on the left disappear. 
All I can see is the starry background. The Green, Orange and Blue buttons are fine.
This happens in the Visual Calculator and the CommNet Planner. 
If I sign out, the problem goes away.
I have tried this on Brave, Edge and Chrome, with the same results.
![KSP Visual Panner problem](https://github.com/user-attachments/assets/87a42709-2b69-43fe-ad29-75c434b59569)

**Comment by 19mw84** [comment]
This also happens on my iphone

**Comment by Blaarkies** [comment]
Sorry I have not been able to reproduce this in chrome. 

Can you please try having a look in the DevTools window to confirm if any errors are logged?
(in Chrome, press F12 to open the DevTools window, then go to the console tab. Any errors logs should show up there)

**Comment by 19mw84** [comment]
![DevToolsKSPVP](https://github.com/user-attachments/assets/eb12654b-fbc2-4f0f-88b5-f183015afcce)

**Comment by Blaarkies** [comment]
Ouch, I think I know what is happening. Each user has a state file (like a savegame), it saves all planet/craft positions so that it can be loaded in when you login.
According to the function calls in that log, it attempted to upgrade your state file from an older version into the new current version. I tested those upgrades with various versions of the app, but I obviously missed something.

A quick work around to fix it:
- Click the orange "CommNet Planner" menu button in the bottom left
- Click "Reset"
- - This will replace your current state file with a fresh new one
- - This also means you lose the old savegame data

In any case, I need to add some proper error handling here, to give the user some options

**Comment by Blaarkies** [comment]
Let me know if the issue persists. With the new fix, it should notify the user of the issue, and load in a fresh new savegame instead

**Comment by 19mw84** [comment]
Thank you. I had a "savegame may be corrupted" warning in the console after that but I deleted the account and started again and all seems to be working now.
Great website by the way! :)
